// The application running on the report's summary page
import { useState, useMemo, useEffect } from "preact/hooks";

import FileBreadcrumbs from "./fileBreadcrumbs";
import FilterToggle from "./filterToggle";
import FlattenToggle from "./flattenToggle";
import getChildData from "./getChildData";
import { setLocation, decodeLocation } from "./routing";
import SummaryHeader from "./summaryHeader";
import SummaryTableHeader from "./summaryTableHeader";
import SummaryTableLine from "./summaryTableLine";
import type { ActiveFilters, ActiveSort, CoverageNode, MetricKey, MetricsToShow } from "./types";

declare global {
  interface Window {
    /** the coverage tree embedded into the page by the html-spa report */
    data: CoverageNode;
    /** the metrics the report was asked to show */
    metricsToShow: MetricKey[];
    /** human-readable generation time embedded into the page */
    generatedDatetime: string;
  }
}

let firstMount = true;

export default function App() {
  const sourceData = window.data;
  const metricsToShow = useMemo(() => {
    const selected: MetricsToShow = {};
    for (let i = 0; i < window.metricsToShow.length; i++) {
      selected[window.metricsToShow[i]] = true;
    }
    return selected;
  }, []);

  const routingDefaults = decodeLocation();

  const [activeSort, setSort] = useState<ActiveSort>(
    (routingDefaults && routingDefaults.activeSort) || {
      sortKey: "file",
      order: "desc",
    },
  );
  const [isFlat, setIsFlat] = useState((routingDefaults && routingDefaults.isFlat) || false);
  const [activeFilters, setFilters] = useState<ActiveFilters>(
    (routingDefaults && routingDefaults.activeFilters) || {
      low: true,
      medium: true,
      high: true,
    },
  );
  const [expandedLines, setExpandedLines] = useState<string[]>(
    (routingDefaults && routingDefaults.expandedLines) || [],
  );
  const [fileFilter, setFileFilter] = useState(
    (routingDefaults && routingDefaults.fileFilter) || "",
  );
  const childData = useMemo(
    () => getChildData(sourceData, metricsToShow, activeSort, isFlat, activeFilters, fileFilter),
    [activeSort, isFlat, activeFilters, fileFilter],
  );
  const overallMetrics = sourceData.metrics;

  useEffect(() => {
    setLocation(firstMount, activeSort, isFlat, activeFilters, fileFilter, expandedLines);
    firstMount = false;
  }, [activeSort, isFlat, activeFilters, fileFilter, expandedLines]);

  useEffect(() => {
    window.onpopstate = () => {
      const routingState = decodeLocation();
      if (routingState) {
        // preact batches these state updates into a single render on its own
        setFilters(routingState.activeFilters);
        setSort(routingState.activeSort);
        setIsFlat(routingState.isFlat);
        setExpandedLines(routingState.expandedLines);
        setFileFilter(routingState.fileFilter);
      }
    };
  }, []);

  return (
    <div className="layout">
      <div className="layout__section">
        <SummaryHeader metrics={overallMetrics} metricsToShow={metricsToShow} />
      </div>
      <div className="layout__section">
        <div className="toolbar">
          <div className="toolbar__item">
            <FlattenToggle setIsFlat={setIsFlat} isFlat={isFlat} />
          </div>
          <div className="toolbar__item">
            <FilterToggle activeFilters={activeFilters} setFilters={setFilters} />
          </div>
        </div>
      </div>
      <div className="layout__section">
        <h1>
          <FileBreadcrumbs fileFilter={fileFilter} setFileFilter={setFileFilter} />
        </h1>
      </div>
      <div className="layout__section layout__section--fill">
        <table className="coverage-summary">
          <SummaryTableHeader
            onSort={(newSort) => {
              setSort(newSort);
            }}
            activeSort={activeSort}
            metricsToShow={metricsToShow}
          />
          <tbody>
            {childData.map((child) => (
              <SummaryTableLine
                {...child}
                key={child.file}
                metricsToShow={metricsToShow}
                expandedLines={expandedLines}
                setExpandedLines={setExpandedLines}
                fileFilter={fileFilter}
                setFileFilter={setFileFilter}
              />
            ))}
          </tbody>
        </table>
      </div>
      <div className="layout__section center small quiet">
        Code coverage generated by{" "}
        <a href="https://istanbul.js.org/" target="_blank" rel="noopener noreferrer">
          istanbul
        </a>{" "}
        at {window.generatedDatetime}
      </div>
    </div>
  );
}
