import "./ReportFooter.css";

function npmPackageVersionUrl(packageName: string, packageVersion: string): string {
  return `https://www.npmjs.com/package/${packageName}/v/${encodeURIComponent(packageVersion)}`;
}

function formatGeneratedAt(value: string | undefined): string {
  const date = value ? new Date(value) : new Date();
  if (Number.isNaN(date.getTime())) {
    return value ?? new Date().toISOString();
  }
  return new Intl.DateTimeFormat(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(date);
}

export interface ReportFooterProps {
  generatedAt?: string;
  packageName?: string;
  packageVersion?: string;
}

export function ReportFooter({ generatedAt, packageName, packageVersion }: ReportFooterProps) {
  const hasPackageInfo = Boolean(packageName && packageVersion);

  return (
    <footer className="report-footer" aria-label="Report metadata">
      <p className="report-footer__meta">
        Code coverage generated by{" "}
        <a
          href="https://github.com/vitest-dev/istanbuljs"
          target="_blank"
          rel="noopener noreferrer"
        >
          istanbul
        </a>
        {hasPackageInfo ? (
          <>
            <span className="report-footer__sep" aria-hidden="true">
              ·
            </span>
            <a
              href={npmPackageVersionUrl(packageName!, packageVersion!)}
              target="_blank"
              rel="noopener noreferrer"
            >
              {packageName} v{packageVersion}
            </a>
          </>
        ) : null}
        <span className="report-footer__sep" aria-hidden="true">
          ·
        </span>
        <time dateTime={generatedAt ?? undefined}>{formatGeneratedAt(generatedAt)}</time>
      </p>
    </footer>
  );
}
